flight_delay_intelligence:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: flight_catalog          # Unity Catalog name
      schema: gold                    # default schema
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

    prod:
      type: databricks
      catalog: flight_catalog
      schema: gold
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
